version: "3.8"
services:
  db:
    image: postgres
    container_name: esok-db-container
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: esok
      POSTGRES_PASSWORD: es921hfbzmai1829hfu89128y9hdfg
      TZ: Europe/Warsaw
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
   
networks:
  default:
    name: esok-network
    external: true