version: "3.8"
services:
  db:
    image: postgres
    container_name: esok-db-container
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: esok
      POSTGRES_PASSWORD: es921hfbzmai1829hfu89128y9hdfg
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-data:
  pgadmin-data:
   
networks:
  default:
    name: esok-network
    external: true